### ISSUE TITLE
Can I make login with this lib?

### ISSUE THREAD

**Issue by Katekko** [l7ssha/nyxx#103]
When I say loggin, I'm speaking about user login, and not with a bot. Like using my token instead the bot's token

**Comment by l7ssha** [comment]
No, and won't be supported

**Comment by thetayloredman** [comment]
> When I say loggin, I'm speaking about user login, and not with a bot. Like using my token instead the bot's token

That would be against TOS.

**Comment by Katekko** [comment]
@thetayloredman Today exist a lib that can do this and I guess is totally legal.

discord.js
https://discord.js.org/#/

But use JS and I'm dart developer, is more easy to me make things with dart then js...

**Comment by l7ssha** [comment]
@Katekko no, logging as user is against TOS and always will be. Anyways keep conversation in topic. That's not place for that.
