### ISSUE TITLE
Any way to create a text channel using Nyxx version 1.1

### ISSUE THREAD

**Issue by Molkars** [l7ssha/nyxx#104]
Is there any way to create a text channel in Nyxx version 1.1? I looked around guild.dart and saw there was no createChannel method like there was in version 1.0.2.

**Comment by l7ssha** [comment]
Apparently it's gone. Must have been lost in the process

**Comment by Molkars** [comment]
Okay, I'm an extension and just copying the method from the development channel. Is the internal `_httpClient` exposed to the public api in any way?

**Comment by l7ssha** [comment]
It is not directly and won't be. You can access IHttpEndpoints interface from Nyxx instance.

**Comment by l7ssha** [comment]
Added endpoint back. Closing issue.
