### ISSUE TITLE
Dart 2.10 regression breaks nyxx

### ISSUE THREAD

**Issue by SecareLupus** [l7ssha/nyxx#106]
**Describe the bug**
Dart removed the --no-null-safety flag from version 2.10, which Nyxx required to function.

**To Reproduce**
1. Install Dart 2.10.x
1. Attempt to run the example pingpong bot, adding arguments ["--enable-experiment=non-nullable", "--no-null-safety"] to the dartvm command. I have used VSCode to add them, hence their current format.
1. Error encountered: Setting VM flags failed: Unrecognized flags: null-safety <linebreak> Exited (255)
1. Removing --no-null-safety from the list of VM flags continues to fail.

**Expected behavior**
Expected the bot to start up once the VM flags were properly set.

**Desktop (please complete the following information):**
 - OS: Debian 10 Linux
 - Dart version 2.10
 - Nyxx version 1.0.2 & git latest

**Comment by l7ssha** [comment]
1.0.x doesn't work on Dart 2.10, either use sdk 2.9.x or use nyxx 1.1 from github with sdk 2.12.
Take a look here: https://github.com/l7ssha/nyxx/issues/98

**Comment by SecareLupus** [comment]
> 1.0.x doesn't work on Dart 2.10

Yes, that was why I was opening a ticket, because presumably this is not the intended functionality of the library, whether it's a regression in your library or in Dartlang proper. If all the tickets regarding this issue are closed because it's not your problem, you're going to run into a lot of people not realizing that it doesn't work right now, and having to figure that out for themselves by following install instructions and not understanding why it's failing.

**Comment by l7ssha** [comment]
Yeah, thats why that issue i linked is pinned. I cant do anything about that at the moment so it is how it is

**Comment by l7ssha** [comment]
Prerelease version of Dart 1.1 is now available in pub: https://pub.dev/packages/nyxx/versions/1.1.0-dev.1. It requires dev sdk 2.12

**Comment by One-Nub** [comment]
I suppose this can be closed since SDK 2.12 is out & the latest versions of Nyxx require the 2.12 SDK or higher.
