### ISSUE TITLE
channel.getFromCache returns null with missing GUILDS intent, causes null check operator exception

### ISSUE THREAD

**Issue by WasserEsser** [l7ssha/nyxx#109]
**Describe the bug**
If you're not specifying the GUILDS intent when construction Nyxx, the bot is unaware of the channels and thus, getFromCache returns null instead of a TextChannel. This causes Commander._handleMessage to throw a 'Null check operator used on a null value' exception when constructing a CommandContext.

**To Reproduce**
Construct a Nyxx instance with only the GUILD_MESSAGES intent, without combining it with the GUILDS intent. Register a command that sends a message in the same channel and the exception should be thrown.

**Expected behavior**
I'm not sure about what to do instead. Can channels be retrieved dynamically? Should an error be thrown instead, notifying the developer of the missing intent?

**Desktop (please complete the following information):**
 - OS: Windows
 - Dart: 2.13.0-59.0.dev
 - nyxx: 1.1.0-dev.3
 - nyxx_commander: 1.1.0-dev.2
 - nyxx_extensions: 1.1.0-dev.3
 - nyxx_interactions: 1.1.0-dev.2

**Comment by l7ssha** [comment]
Maybe commander should check for intents, and it wont start without specific intents (all inprivileged). Thats the most sensible i think.

**Comment by l7ssha** [comment]
Fixed with 79035b3. Thanks for reporting issue :)
