### ISSUE TITLE
Bot disconnects itself after a while

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#11]
Hey there, it's been a while. 

I'm having issues with the bot disconnecting itself for no reason after some time of inactivity.  
I'm currently running it inside a tmux session on a dedicated server on Debian 8 but the same issue occurs with Docker.

These are the only logs I've got for the bot, and as you can see it's supposed to have been running for 12 days.
```
▶ dart bin/main.dart
[FINE]  {CommandsFramework} - 3.10.2018 15:12:45:734 -- Command [mp] has been registered
[FINE]  {CommandsFramework} - 3.10.2018 15:12:45:745 -- Command [game] has been registered
[FINE]  {CommandsFramework} - 3.10.2018 15:12:45:746 -- Command [player] has been registered
[FINE]  {CommandsFramework} - 3.10.2018 15:12:45:747 -- Command [update] has been registered
[FINE]  {CommandsFramework} - 3.10.2018 15:12:45:748 -- Command [doodle] has been registered
[INFO]  {Client} - 3.10.2018 15:12:47:125 -- Connected and ready!
Ready!
```
However it's unresponsive to commands and is logged off

![image](https://user-images.githubusercontent.com/3439246/46935906-e86fa680-d05c-11e8-816d-82a71306ff9f.png)

Do you have any idea or suggestion?

**Comment by l7ssha** [comment]
Bot cannot disconnect itself or something like that. Maybe your server suspends process. I have bot running correctly for 24h and another for 18h. Can you setup some message logging, or/and periodic timer to print check if program is running.

For ex:
```dart
Timer.periodic(const Duration(minute: 1), (t) => print(bot.guilds.count));
```

**Comment by Outpox** [comment]
I'm going to add some periodic logging and will get back to you, thanks.

**Comment by Outpox** [comment]
I don't understand, I've had the process opened in a terminal the whole time, it kept printing to the console but the bot still went offline.

```
▶ dart bin/main.dart
[FINE]  {CommandsFramework} - 15.10.2018 10:29:38:234 -- Command [mp] has been registered
[FINE]  {CommandsFramework} - 15.10.2018 10:29:38:245 -- Command [game] has been registered
[FINE]  {CommandsFramework} - 15.10.2018 10:29:38:247 -- Command [player] has been registered
[FINE]  {CommandsFramework} - 15.10.2018 10:29:38:248 -- Command [update] has been registered
[FINE]  {CommandsFramework} - 15.10.2018 10:29:38:249 -- Command [doodle] has been registered
[INFO]  {Client} - 15.10.2018 10:29:39:781 -- Connected and ready!
Ready!
2018-10-15 10:44:38.310004 still alive?
2018-10-15 10:59:38.309588 still alive?
2018-10-15 11:14:38.309594 still alive?
2018-10-15 11:29:38.309588 still alive?
2018-10-15 11:44:38.309584 still alive?
2018-10-15 11:59:38.309579 still alive?
2018-10-15 12:14:38.309577 still alive?
2018-10-15 12:29:38.309579 still alive?
2018-10-15 12:44:38.309567 still alive?
2018-10-15 12:59:38.309564 still alive?
2018-10-15 13:14:38.309554 still alive?
2018-10-15 13:29:38.309544 still alive?
2018-10-15 13:44:38.309576 still alive?
2018-10-15 13:59:38.309557 still alive?
2018-10-15 14:14:38.309555 still alive?
2018-10-15 14:29:38.309570 still alive?
```

![image](https://user-images.githubusercontent.com/3439246/46951349-0272ae80-d088-11e8-8af2-fa0b953cd6e9.png)

**Comment by l7ssha** [comment]
I found just now problems with sessions invalidating right after `READY` event. 
Can you create listener to `onDisconnect` event? With close code and shard number.

**Comment by Outpox** [comment]
I will do that later today yes ;-)

**Comment by l7ssha** [comment]
Are you setting presence for your bot? Gateway disconnects me due invalid opcode when sending `STATUS_UPDATE`.

**Comment by Outpox** [comment]
Nope, I'm not setting the bot's presence. I'll have a look on how to set it.

**Comment by l7ssha** [comment]
Pushed possibly fix for this problem. Please test against latest commit.

**Comment by Outpox** [comment]
I've update my code for the newest Nyxx version and it seems to be working on my local machine. I'll run it tonight on my server and will let you know ;-)

**Comment by Outpox** [comment]
The bot is still connected and responsive to commands (12h uptime) so I'd say it looks promising!  
I don't know if it's relevant to you but I've had the following log several times:
```
UNKNOWN OPCODE: {"t":"GUILD_INTEGRATIONS_UPDATE","s":2577,"op":0,"d":{"guild_id":"450704289141358607"}}
```

**Comment by l7ssha** [comment]
That's okay - ignore it. I'm just logging these to notice about them.
