### ISSUE TITLE
context.getArguments() breaks with command aliases

### ISSUE THREAD

**Issue by WasserEsser** [l7ssha/nyxx#111]
context.getArguments() currently only works with the default command name.
This is because it removes the prefix + fullCommandName from the message and takes the rest as arguments. With aliases however, there could be multiple combinations of fullCommandName.

Think of a CommandGroup with name 'hello' and an alias of 'h', with a subCommandEntity with the name 'world' and the alias 'w'.

This would mean that the command can be triggered by 'hello world', 'hello w', 'h world' and 'h w', but getting the arguments only works in the case of 'hello world'.

**Comment by l7ssha** [comment]
all right, I see problem here. Will take a look today :)

**Comment by l7ssha** [comment]
Fixed with 79035b3. Thanks for reporting issue :)
