### ISSUE TITLE
Nyxx.users doesn't get populated from message events

### ISSUE THREAD

**Issue by WasserEsser** [l7ssha/nyxx#112]
Currently, it looks like the users cache doesn't get populated at all.
ClientOptions.forceFetchUsers has no effect. Additionally, ClientOptions.cacheMembers doesn't make fetchUser add the user to Nyxx.users.

**Comment by WasserEsser** [comment]
So in my case, bot.users is always an empty map.

**Comment by l7ssha** [comment]
First of all: intents - without them you wont receive member chunks
As of 
> ClientOptions.cacheMembers doesn't make fetchUser add the user to Nyxx.users
it is probably a bug. Will take a look

**Comment by WasserEsser** [comment]
> First of all: intents - without them you wont receive member chunks
> As of
> 
> > ClientOptions.cacheMembers doesn't make fetchUser add the user to Nyxx.users
> > it is probably a bug. Will take a look

I'm using the GUILD_MEMBERS intent.

**Comment by l7ssha** [comment]
You need also to set up MemberCachePolicy in Nyxx constructor. By default only caches bot owner and users in voice.

**Comment by l7ssha** [comment]
> ~You need also to set up MemberCachePolicy in Nyxx constructor. By default only caches bot owner and users in voice.~
Seems like bot.users not cached is antoher bug. My message above is refering to members not users. Something is lost in the process then. @WasserEsser

**Comment by l7ssha** [comment]
Result of `fetchUser` methods are not cached and probably won't be because I think there is no need for that.
> Currently, it looks like the users cache doesn't get populated at all.

Can't really confirm that, currently `Running on Dart` bot caches users just fine from message events. I'll need more info with a way to reproduce issue

> ClientOptions.forceFetchUsers has no effect. Additionally, ClientOptions.cacheMembers doesn't make 

These are not supported currently due gateway intents. Also `ClientOptions.cacheMembers` only affects `fetchMember` not `fetchUser`.

**Comment by WasserEsser** [comment]
> Result of `fetchUser` methods are not cached and probably won't be because I think there is no need for that.
> 
> > Currently, it looks like the users cache doesn't get populated at all.
> 
> Can't really confirm that, currently `Running on Dart` bot caches users just fine from message events. I'll need more info with a way to reproduce issue
> 
> > ClientOptions.forceFetchUsers has no effect. Additionally, ClientOptions.cacheMembers doesn't make
> 
> These are not supported currently due gateway intents. Also `ClientOptions.cacheMembers` only affects `fetchMember` not `fetchUser`.

I'm sorry for rushing this issue without properly investigating myself, I had to go so I didn't investigate much, only looked if variables were being referenced in the source code. Sorry for making you investigate something that I should've spent more time researching first. I also didn't think about the difference between members and users, I do get it now.

After looking into this a bit more, I found out that the list of users is empty because a MessageReceivedEvent does not add the user to the cache. A TypingEvent does, which is why it sometimes works, and sometimes doesn't (depending on how fast the message was typed and if the typing event was sent or not).

**Comment by l7ssha** [comment]
Fix is pushed. After my final testing I will push version to pub. Thanks for reporting :)
