### ISSUE TITLE
Add a max constraint to dart sdk

### ISSUE THREAD

**Issue by gabrielpacheco23** [l7ssha/nyxx#116]
Would this maybe solve some version problems?
Just adding 
```yaml 
environment:
  sdk: '>=2.12.0 <3.0.0'
```

**Comment by l7ssha** [comment]
What version problems? [2.0.0-rc.3](https://pub.dev/packages/nyxx/versions/2.0.0-rc.3) already supports 2.12 and future versions of sdk (https://github.com/l7ssha/nyxx/blob/dev/nyxx/pubspec.yaml#L10)

**Comment by gabrielpacheco23** [comment]
> What version problems? [2.0.0-rc.3](https://pub.dev/packages/nyxx/versions/2.0.0-rc.3) already supports 2.12 and future versions of sdk (https://github.com/l7ssha/nyxx/blob/dev/nyxx/pubspec.yaml#L10)

Versions higher than the stable branch, like 2.14.3 (dev branch).

I tried with 2.14.3-dev.

**Comment by l7ssha** [comment]
Fixed in https://github.com/l7ssha/nyxx/commit/a1bda440ef2671d3536d6d0be88119f51ef2627e
Seems like pub behaves little weird with versionins, because `>=2.12.0` should allow anything higher that 2.12, according to semver. 
Each package will also release new version on pub.
