### ISSUE TITLE
[Enhancement] Cache and Events refactor

### ISSUE THREAD

**Issue by HarryET** [l7ssha/nyxx#124]
Looking into the events and cache system to refact it for better useability & efficiency

**Comment by arslee07** [comment]
+1

Listeners really need refactoring to be separable and reusable

**Comment by HarryET** [comment]
In what way? You can already make a listener in a separate function/file.

**Comment by HarryET** [comment]
This Issue is being closed as I am holding it off till post v2.0 stable release.
