### ISSUE TITLE
Slash Commands Embed Empty

### ISSUE THREAD

**Issue by aarongarnerm** [l7ssha/nyxx#136]
**Describe the bug**
When using ComponentMessageBuilder inside of a SlashCommandInteractionEvent it ignores all data from an embed. If you have no content set you will recieve this error "[2021-06-07 05:33:25.645669] [SEVERE] [Client] ERROR: [Code: 400] [Message: {"message": "Cannot send an empty message", "code": 50006}]". If you do have Content set it will send the content and ignore the embed without error message.

**To Reproduce**
Put the files accordingly in a new project. Make sure to change the file extensions to ".dart" as GitHub won't accept the file extension, I changed them to text files. When you get in the files, you will need to locate the app.dart file. Add your token at line 9. Add your guild id that you will reproduce the error at line 14.

**Expected behavior**
When sending /info into the server the bot should respond with an Embed that has the title set to "Which would you like to choose".

**Desktop:**
 - OS: [Windows 10 Pro 20H2]
 - Dart version [2.13.1]
 - Nyxx version [2.0.0-rc.5]
 
**This file is in the bin folder**
[app.txt](https://github.com/l7ssha/nyxx/files/6608071/app.txt)

**These files are in the lib folder**
[docs.txt](https://github.com/l7ssha/nyxx/files/6608077/docs.txt)
[info.txt](https://github.com/l7ssha/nyxx/files/6608078/info.txt)
[info-slash.txt](https://github.com/l7ssha/nyxx/files/6608080/info-slash.txt)
[utils.txt](https://github.com/l7ssha/nyxx/files/6608081/utils.txt)

**PUBSEC**
[pubspec.txt](https://github.com/l7ssha/nyxx/files/6608118/pubspec.txt)

**Comment by HarryET** [comment]
Thanks, will look into more later for now just stick to content. Will post updates here 🙂 It's sending:
```json
{
  // .....
  "embed": {}
}
```
I believe it should be sending:
```json
{
  // .....
  "embeds": [
    {}
  ]
}
```
Because it's a webhook.

**Comment by HarryET** [comment]
Should be fixed, @aarongarnerm please test then close if fixed.

**Comment by l7ssha** [comment]
Issue fixed and original author doesnt provided further feedback. Closing
