### ISSUE TITLE
Guild.fetchMembers() not pulling members.

### ISSUE THREAD

**Issue by Technicolor-creamsicle** [l7ssha/nyxx#138]
**Describe the bug**
When fetching members using `Guild.fetchMembers()` the stream will not contain any members.

**To Reproduce**

For an easier way to reproduce I made a slim example bot:
```dart
import 'package:nyxx/nyxx.dart';
import 'package:nyxx_commander/commander.dart';

void main(List<String> args) {
  var token = 'TOKEN GOES HERE';
  var bot = Nyxx(token, 32511);

  Commander(bot, prefix: '//').registerCommand('fetchMembers',
      (context, message) async => Command.fetchMembers(context, message));
}

class Command {
  static void fetchMembers(CommandContext context, String message) async {
    await for (Member member in context.guild!.fetchMembers(limit: 10)) {
      print('rxed member');
      await context.channel.sendMessage(
          MessageBuilder.content('Member ${member.nickname} found'));
    }
  }
}
```
**Expected behavior**
With the example above when the command `//fetchMembers` is run it should respond with a maximum of 10 usernames (also shown in console with 'rxed member') of members in the guild it is run in.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS
 - Dart version 2.13.3
 - Nyxx version 2.0.0-rc.9
 - Nyxx_Commander 2.0.0-rc.8

**Additional context**
None

**Comment by HarryET** [comment]
Thanks will try to reproduce when I have some free time later 😃

**Comment by Technicolor-creamsicle** [comment]
Your welcome, tried to make it as easy to reproduce as possible. :)



________________________________

**Comment by One-Nub** [comment]
Could reproduce - looks like there's a missing `await` on [this line](https://github.com/l7ssha/nyxx/blob/2b9796c478d3b790dac28419b89dfbd2577d3077/nyxx/lib/src/internal/_HttpEndpoints.dart#L724). It may be worthwhile checking for any other instances where an `await` may be missing where it could be needed to bundle a fix.
