### ISSUE TITLE
Commander Context Guild is null

### ISSUE THREAD

**Issue by Mirageofmage** [l7ssha/nyxx#148]
**Describe the bug**
When accessing the guild from the context of a command from Commander, it returns null

**To Reproduce**
```
final bot = Nyxx([Token], GatewayIntents.allUnprivileged);
var c = Commander(bot, prefix: '%');

var cGroup = CommandGroup(name: 'commandGroup', aliases: ['q']);

cGroup.registerSubCommand('subCommand', (context, message) => {
        context.sendMessage(MessageBuilder.content('Some Text : ${context.guild.id.toString()}')),  // <- Fails due to guild == null;
});
```

**Expected behavior**
I should be able to access the guild information

**Desktop (please complete the following information):**
 - OS: macOS 11.4 (20F71)
 - OS: Ubuntu 16.04.7 LTS (gcloud)
 - Dart version: 2.14.0-48.0.dev
 - Nyxx version 
  nyxx: ^2.0.0-rc.10
  nyxx_commander: ^2.0.0-rc.10
  nyxx_interactions: ^2.0.0-rc.13

**Additional context**
The bot has Administrator permissions. 
This was working on older versions of Nyxx
I can access other properties of context, such as message just fine

**Comment by HarryET** [comment]
Thanks, looking into now. Will try repro :)

**Comment by HarryET** [comment]
Ok this is the designed behaviour see:
https://github.com/l7ssha/nyxx/blob/dev/nyxx_commander/lib/src/CommandContext.dart#L15
https://github.com/l7ssha/nyxx/blob/dev/nyxx_commander/lib/src/Commander.dart#L119

The guild on the context is nullable and in the commander it tries to get the guild from cache only if not found returning null which means the guild must not be in your cache. If you get the message and do:
```dart
final bot = Nyxx([Token], GatewayIntents.allUnprivileged);
var c = Commander(bot, prefix: '%');

var cGroup = CommandGroup(name: 'commandGroup', aliases: ['q']);

cGroup.registerSubCommand('subCommand', (context, message) => {
        final guild = await context.message.guild.getOrDownload()
        context.sendMessage(MessageBuilder.content('Some Text : ${guild.id.toString()}')),
});
```
That should work for you.

**Comment by Mirageofmage** [comment]
> Ok this is the designed behaviour see:
> https://github.com/l7ssha/nyxx/blob/dev/nyxx_commander/lib/src/CommandContext.dart#L15
> https://github.com/l7ssha/nyxx/blob/dev/nyxx_commander/lib/src/Commander.dart#L119
> 
> The guild on the context is nullable and in the commander it tries to get the guild from cache only if not found returning null which means the guild must not be in your cache. If you get the message and do:
> 
> ```dart
> final bot = Nyxx([Token], GatewayIntents.allUnprivileged);
> var c = Commander(bot, prefix: '%');
> 
> var cGroup = CommandGroup(name: 'commandGroup', aliases: ['q']);
> 
> cGroup.registerSubCommand('subCommand', (context, message) => {
>         final guild = await context.message.guild.getOrDownload()
>         context.sendMessage(MessageBuilder.content('Some Text : ${guild.id.toString()}')),
> });
> ```
> 
> That should work for you.

"The getter 'guild' isn't defined for the type 'Message'.
Try importing the library that defines 'guild', correcting the name to the name of an existing getter, or defining a getter or field named 'guild'."

I can't directly do context.guild.getOrDownload() either.

Checking the Message class there's no field for guild, but there is for GuildMessage which I'm assuming is the class that's supposed to be used there? In which case context.message isn't returning the correct class?

**Comment by HarryET** [comment]
You need to check if the .message is a guild message if it is cast it to a GuildMessage

**Comment by Mirageofmage** [comment]
Is it intended for messages sent by webhooks to be registered as a DM?

`_CastError (type 'DMMessage' is not a subtype of type 'GuildMessage' in type cast)`

All my issues seem to really come down to this. The same message sent by a user works just fine.

**Comment by l7ssha** [comment]
> Is it intended for messages sent by webhooks to be registered as a DM?
its just like that because guild id wasnt sent with message payload. Naming maybe is a little unfortunate in that case, but it comes down to that message doesn't have any guild info, besides that it was sent in guild

**Comment by Mirageofmage** [comment]
Is this an issue from Discord's side then? The guild info should be included with the registered webhook from their end, not with the request. A simple JSON like 
`{"content": "%springbok"}` should work?

**Comment by l7ssha** [comment]
`guild_id` in message in optional (https://discord.com/developers/docs/resources/channel#message-object-message-structure) so nothing we can do really.

> The guild info should be included with the registered webhook from their end, not with the request. A simple JSON like
{"content": "%springbok"} should work?

I dont really understand about what are you talking there. Seems like out of scope of this issue

**Comment by HarryET** [comment]
> Is this an issue from Discord's side then? The guild info should be included with the registered webhook from their end, not with the request. A simple JSON like
> `{"content": "%springbok"}` should work?

This dosen't make any sense, Unless you have a docs link to explain what you are trying to explain?

**Comment by Mirageofmage** [comment]
Closing for off topic, but here's a [docs](https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html) page to what I'm trying to explain. 

The webhook in Discord is already registered to a guild and a channel, what I don't understand is why this info is no longer readable by the library (it used to be)
