### ISSUE TITLE
No way to fetch Roles.

### ISSUE THREAD

**Issue by Technicolor-creamsicle** [l7ssha/nyxx#152]
**Is your feature request related to a problem? Please describe.**
When trying to manage a role on a server or count how many users are in the role there is no way to ensure that the bot has the role in the cache.

**Describe the solution you'd like**
A `fetchRole()` method to be added.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by HarryET** [comment]
Will do, @l7ssha assign me please

**Comment by l7ssha** [comment]
Fixed in #153
