### ISSUE TITLE
Use of singleton bot within library

### ISSUE THREAD

**Issue by Benny-** [l7ssha/nyxx#18]
Nyxx is object oriented but different parts of the library all reference the singleton Nyxx bot instance. This leads to problems when creating multiple bots.

For this issue to be resolved, the internal library no longer needs to reference this Nyxx singleton.

**Comment by Benny-** [comment]
I am willing to take this issue upon myself. My use case requires it.

**Comment by l7ssha** [comment]
Resolved in https://github.com/l7ssha/nyxx/commit/ede6355dd2b16df427dc94d28a8dabe2096abc48
