### ISSUE TITLE
Exponential backoff

### ISSUE THREAD

**Issue by Benny-** [l7ssha/nyxx#27]
At the moment Nyxx reconnects quickly after failures.

I'd suggest to change this to a exponential back-off algorithm so it doesn't waste too much resources if it gets into a failure loop.

As it stands I received an email from discord; they had to reset my bot token after 1000 connection attempts while I left the bot on overnight.

**Comment by l7ssha** [comment]
Related #17

**Comment by l7ssha** [comment]
Fixed: https://github.com/l7ssha/nyxx/releases/tag/0.3.0
