### ISSUE TITLE
Incompatible with Dart >=2.0.0

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#3]
Hey there!
I've been trying to use this lib for a simple test project but had the following issue trying to install it:   
```
[discord_dart] pub get
Resolving dependencies...
The current Dart SDK version is 2.0.0.

Because nyxx >=0.24.0 depends on w_transport >=1.0.1 which requires SDK version <2.0.0, nyxx >=0.24.0 is forbidden.
So, because discord_dart depends on nyxx 0.24.0, version solving failed.
exit code 1
```
`nyxx` is the sole dependency I've got in my `pubspec.yml`.  
  
I've just checked and the `w_transport` package (even in its `3.2.6` version) requires 
```
environment:
    sdk: ">=1.14.0 <2.0.0"
```
so this issue is here. Do you have any plan to use something else?

**Comment by Outpox** [comment]
Damn I'm sorry I've just found the `dart2.0` branch :D  
Do you have any idea of when you'll publish this new branch in place of the "older" one?

**Comment by Outpox** [comment]
Alright! Take your time I'm not in a hurry.  
I'll leave it up to you if you want to close the issue now or if you want to keep it as a reference for the updates.

**Comment by l7ssha** [comment]
Latest commit from this branch should all compatibility issues. Nyx is built with latest stable dart sdk. Make sure you are pulling nyxx from git:
```yaml
dependencies:
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: backend_rework
```

I'll leave this issue as refernce.

**Comment by l7ssha** [comment]
Fixed. https://github.com/l7ssha/nyxx/releases/tag/0.3.0
