### ISSUE TITLE
Spoilers

### ISSUE THREAD

**Issue by l7ssha** [l7ssha/nyxx#31]
TODO: 
 - [x] Helper method for attaching files as spoilers
 - [x] Helper for creating text spoilers
 - [ ] Parsing spoilers in message

**Comment by Benny-** [comment]
The spoiler tags belong to discord's markdown flavor. How the spoilers will be rendered depend on the platform on which it will be shown. Eg. web, desktop or android.

I assert that Nyxx can't do much or should do anything with regard to parsing the spoilers in the messages. Instead I think it's best to let the consumer of Nyxx handle the parsing by extending a existing markdown processor.

**Comment by l7ssha** [comment]
I think at least we should implement method to check if messsage contains any spoilers. Other libs (like [Javacord](https://github.com/Javacord/Javacord/pull/435)) have extended support for that thing.

**Comment by sirhypernova** [comment]
For now, an easy way to send an image as a spoiler is to prefix the name with `SPOILER_`

**Comment by Benny-** [comment]
Javacord's issue doesn't seem to be about checking if messages contain spoilers. It deals with sending spoilers and spoiler attachments.

**Comment by burdoto** [comment]
@Benny- It does have that, though. The Issue over at Javacord is about overall Spoiler implementation.
See:
- https://github.com/Javacord/Javacord/pull/435/files#diff-3d91bc1505a58db511f663a5fdc0c18bR93
- https://github.com/Javacord/Javacord/pull/435/files#diff-6951af4a6d046cee9ac4a6fe06828938R158

**Comment by Benny-** [comment]
@burdoto But does it deal with the message content?

**Comment by Saladoc** [comment]
It doesn't. We add "SPOILER" to our [MessageDecoration Enum](https://github.com/Javacord/Javacord/pull/435/files#diff-a8862f9fee1a17498209c60ee3cbcfb0) which contains the markdown formatting possibilities (besides URLs as that only works in embeds). It being present there allows text spoilers to be written via our `MessageBuilder`.
Apart from that we detect if an *attachment* is a spoiler and allow attaching spoilers in the `MessageBuilder`.
