### ISSUE TITLE
Command still fires when there is text directly after it

### ISSUE THREAD

**Issue by sirhypernova** [l7ssha/nyxx#32]
![screenshot from 2019-02-01 16-58-18 1](https://user-images.githubusercontent.com/18422972/52154281-c5d0c000-2642-11e9-82e2-89ee0b62780d.png)

Here is a screenshot

**Comment by sirhypernova** [comment]
This is in the `development` branch, I forgot to state that

**Comment by l7ssha** [comment]
I'll take a look today. Should be pretty easy to fix. I guess I put somewhere `startsWith` instead of `==`.

**Comment by l7ssha** [comment]
@sirhypernova are you using `CommandParser`?

**Comment by l7ssha** [comment]
![image](https://user-images.githubusercontent.com/23033957/52155304-5d093800-2682-11e9-8bee-83b3fbe42a7b.png)
Fix will be in next commit. Thanks for bug report.

**Comment by sirhypernova** [comment]
Thank you :smiley:

**Comment by sirhypernova** [comment]
![screenshot from 2019-02-01 17-57-45](https://user-images.githubusercontent.com/18422972/52155971-0cc2b380-264b-11e9-91d0-6a75b6bcdb5e.png)
Hello, sorry to bother you again! I updated to the latest version. It seems to respond still, and now message editing no longer works. Any ideas?
