### ISSUE TITLE
Issue with embeds

### ISSUE THREAD

**Issue by sirhypernova** [l7ssha/nyxx#33]
In commit [4532f5d](https://github.com/l7ssha/nyxx/commit/4532f5dfb7ddbbcfdfbd48321e7b3b86cc752c2f), embeds without fields will not send. The error is `Bad state: No element`. If I had to guess, at some point you are trying to check field values without verifying they exist (?). Thanks :)

**Comment by l7ssha** [comment]
Yeah. There is missing null check somewhere. Will be fixed in few minutes

**Comment by sirhypernova** [comment]
Alright thanks
