### ISSUE TITLE
I can't use example

### ISSUE THREAD

**Issue by dennougorilla** [l7ssha/nyxx#39]
I can't use `NyxxVm`.
And I use `Nyxx('MY_DISCORD_TOKEN')`;
But returned 
`NotSetupError: Token is null or empty or bot isn't set properly!`

**Comment by dennougorilla** [comment]
What setup?
`if (!setup || (_token == null || _token.isEmpty)) throw NotSetupError();`
https://github.com/l7ssha/nyxx/blob/322c559b6e0acc6997cd9d0622a4433edcaa60a5/lib/src/nyxx/Nyxx.dart#L186

**Comment by l7ssha** [comment]
Are you pulling nyxx from github? Why you can't use `NyxxVm`?

**Comment by dennougorilla** [comment]
I pulled nyxx from github. I could use NyxxVm!
Thanks 😊
Pub version can't use nyxxVm yet?

**Comment by l7ssha** [comment]
I didn't publish new release yet so it isn't available
