### ISSUE TITLE
Infinite typing in DMs

### ISSUE THREAD

**Issue by One-Nub** [l7ssha/nyxx#45]
Using the command framework, when declaring the command, if the boolean typing is set to `true`, and a restriction is added to prevent the command from running in DMs, if you run the command in a DM anyways the bot will start typing indefinitely. 

Example code: (even something as simple as this does it)
```dart
@Restrict(requiredContext: ContextType.guild)
@Command("error", typing: true)
Future<void> error(CommandContext ctx) async {
  ctx.message.reply(content: "This won't send in a DM; but the bot will type");
}

````

**Comment by l7ssha** [comment]
Fixed in https://github.com/l7ssha/nyxx/commit/5a64a7fd57ce43e295855df945d0bab22fe3cba8
