### ISSUE TITLE
Logging will be broken by dart-lang/logging#71

### ISSUE THREAD

**Issue by jamesderlin** [l7ssha/nyxx#47]
I've recently made a change (https://github.com/dart-lang/logging/pull/71) that affects the behavior of `Logger.detached` from `package:logging`.  This change expected to be included in `logging` 0.11.4.

This change in behavior should not affect most packages, but it appears that it will break logging in the nyxx package.

The recommended fix is to set `Logger.level` and `Logger.onRecord` on the detached `Logger` itself instead of on `Logger.root`. (In general, libraries should leave responsibility for configuring `Logger.root` to the application.)

**Comment by l7ssha** [comment]
Thanks for notice, I'll take care of it.
