### ISSUE TITLE
Library status

### ISSUE THREAD

**Issue by tenhobi** [l7ssha/nyxx#51]
Hi, I like your library, but because it says "build failing" and the updates are not newest, I have a question: is this library managed and stable?

Thanks a lot!

**Comment by l7ssha** [comment]
Library is in 'hibernation state' right now. I'm waiting for dart dev team to implement NNBD. Im currently trying to start implementing non null apis, but as in beta or development state of that there are many issues with that. Look at #43.

**Comment by tenhobi** [comment]
Thank for your comment. Wish you luck. 💙
