### ISSUE TITLE
Parse commands arguments

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#6]
Hey there (it's me again),

I have taken the time to read a good part of the code base and couldn't find this: is it possible to only get the arguments passed to a command?

```
!ping this is a test
```
expected: 
```
print(this.message.arguments) // String "this is a test"
```
The way I see it would be by extending the `Message` class in order to add an `argument` property for example. Although that would require to get the command `prefix` as well as the command itself. What are your thoughts about this?

**Comment by l7ssha** [comment]
If you are using `CommadsFramework` you can specify arguments in method signature or catch all arguments as List or String with `@Remainder()` annotation.

```dart
Future<void> exCmd(CommandContext ctx, String first, int second, @Remainder() String rest) async {
  // Your code 
}
```

If you have your commands in module you dont want `CommandContext` in method signature

**Comment by Outpox** [comment]
I was in fact testing with the `@command.Module` annotation:
```
@command.Module("ping")
class PongCommand extends command.CommandContext {
  @command.Command(main: true)
  @command.Help("Pong!", usage: "ping")
  @command.Remainder()
  Future run() async {
    print("content: '${this.message.content}'");
    await reply(content: "Pong!");
  }
}
```
but I don't get how I am supposed to retrieve the remainder that way.

**Comment by l7ssha** [comment]
Your code should be like
```dart 
@command.Module("ping")
class PongCommand extends command.CommandContext {
  @command.Command(main: true)
  @command.Help("Pong!", usage: "ping")
  Future run(@command.Remainder() String rest) async {
    print("content: '${this.message.content}'");
    await reply(content: "Pong!");
  }
}
```
Remaider should be before method parameter. It can be `String` or `List<String>`

**Comment by Outpox** [comment]
Will give it a try thanks!

**Comment by Outpox** [comment]
It is working as expected! :+1:
