### ISSUE TITLE
Don't always rely on cache

### ISSUE THREAD

**Issue by l7ssha** [l7ssha/nyxx#61]
Due new feature of gateway called intents caches cant be always populated with data. Also when user disables cache, there wont be data in many cases available in events. Library should deserialize objects if no cache is available

**Comment by l7ssha** [comment]
First changes related to this issue in 6fbd1f1

**Comment by l7ssha** [comment]
Currently working on new internal structure to allow omitting cache whatsoever. It will also include improvements to internal data structure.

**Comment by NDSo** [comment]
Just started using this package (and the Discord API) today.
I encountered a couple cache related bugs but see that you already have the fixes committed.
Keep up the great work.

**Comment by l7ssha** [comment]
Related issue on discord's end: discord/discord-api-docs#1709
