### ISSUE TITLE
Watch for process events and take actions based on event received

### ISSUE THREAD

**Issue by l7ssha** [l7ssha/nyxx#67]
Refernce to [ProcessSignal](https://api.dart.dev/stable/2.8.1/dart-io/ProcessSignal-class.html) class which can be used to implement that.
When receiving SIGKILL or SIGTERM bot should close connection(s) to gateway (and set its status to offline maybe) and then close.

**Comment by One-Nub** [comment]
[SIGKILL can't be caught](https://api.dart.dev/stable/2.8.1/dart-io/ProcessSignal/watch.html) and used to close the connection, so SIGTERM would be the best to use in my mind - but windows does not generate this so if a user tries to stop the bot on windows by stopping the process, the bot won't gracefully clean up.

So if we wanted windows & other os support, we could use SIGINT (sent when using Ctrl + C) and close the connection based on that? Or implement both SIGINT and SIGTERM, leaving only forceful killing to be the only method that doesn't gracefully close the bot.

**Comment by l7ssha** [comment]
This feature is also needed because apparently killing main isolate, another isolates used by process aren't killed.

**Comment by l7ssha** [comment]
Isolates spawned by main isolate are immediately closed even when main isolate implements callbacks for SIGTERM and SIGINT, thus connection with gateway cannot be closed gracefully.
