### ISSUE TITLE
Exception when trying to return DMChannel from User.dart

### ISSUE THREAD

**Issue by oelburk** [l7ssha/nyxx#81]
```
Exception has occurred.
StateError (Bad state: No element)
```
is thrown when `return (client.channels.findOne((Channel c) => c is DMChannel && c.recipient.id == this.id) as DMChannel) ?? await downloadChannel();` is called at **row 59**, **User.dart**

Just tried to do a simple try-catch which makes is return null and run `downloadChannel()` correct. Which works fine for me atm but would ofc be better to solve it properly.

Basically I'm just trying to store the dm channel like this;
`var dmChan = await ctx.member.dmChannel;`

Cheers!

**Comment by l7ssha** [comment]
Are you using `rewrite_modular` branch?

**Comment by oelburk** [comment]
Nope, this is 0.30.0. Should I switch?

**Comment by l7ssha** [comment]
Yeah, `0.30.0` is pretty much outdated. Join https://discord.gg/discord-api and head to `#dart_nyxx` for more info.

You will need that code to get nyxx from git, and dart dev sdk.
```
nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: rewrite_modular
      path: nyxx
```
To run code you will need to specify additonal parameters `--enable-experiment=non-nullable --no-null-safety`. Ask in `#dart_nyxx` in discord api guild if you have further questions

**Comment by oelburk** [comment]
Thank's man, will check it out! Closing it now and re-opening if I see it when I've changed branch. Cheers!
