### ISSUE TITLE
member.edit does not change voice channel

### ISSUE THREAD

**Issue by MichealReed** [l7ssha/nyxx#83]
Supplying a voice channel to the edit function does not actually move the user.

simple test code to reproduce below, you may have to type once in chat before the bot begins monitoring voice channels.
```
    bot.onVoiceStateUpdate.listen((VoiceStateUpdateEvent e) async {
      print("event!");
      if (e.state.user.id.id == "id") {
        Guild guild =
            bot.guilds.findOne((item) => item.id.id == "id");
        VoiceChannel afk = guild.channels[Snowflake("id")]
            as VoiceChannel;
            print(afk.name);

            await guild.members[Snowflake("id")].edit(channel:afk);
      }
    });
```

**Comment by l7ssha** [comment]
are you using nyxx from pub or `rewrite_modular` branch?

**Comment by MichealReed** [comment]
pub, should I switch?

**Comment by l7ssha** [comment]
Read here https://github.com/l7ssha/nyxx/wiki. Yeah you should switch, pub is outdated and most like dont even work as intended. Im currently rewriting whole framework, look also here https://github.com/l7ssha/nyxx/pull/43
