### ISSUE TITLE
Get a TextChannel or User from ID

### ISSUE THREAD

**Issue by gabrc52** [l7ssha/nyxx#88]
Is it possible to get a `TextChannel` or `User` from a specific `Snowflake` ID?

I couldn't find how to do this on the documentation.

**Comment by l7ssha** [comment]
https://nyxx.l7ssha.xyz/nyxx/nyxx/Nyxx/channels.html

and 

https://nyxx.l7ssha.xyz/nyxx/nyxx/Nyxx/users.html

**Comment by gabrc52** [comment]
Oh, I see, thank you. 

Should I close this issue?

**Comment by l7ssha** [comment]
Yeah, sure. glad i could help. Remember you can always ask in #dart_nyxx channel in Discord API guild: https://discord.gg/discord-api
