### ISSUE TITLE
Support INVITE_CREATE

### ISSUE THREAD

**Issue by gabrc52** [l7ssha/nyxx#89]
Every time someone creates an invite a line gets printed saying:

    UNKNOWN_OPCODE: {"t":"INVITE_CREATE", ... }

It would be nice to have an `onInviteCreated`

**Comment by l7ssha** [comment]
https://github.com/l7ssha/nyxx/wiki#attention - Its implementaed in `rewrite_modular` branch - Not yet released because of implications of current dart support of nnbd and lacks of tooling.
