### ISSUE TITLE
EmbedBuilder.fromJSON

### ISSUE THREAD

**Issue by HIHIQY1** [l7ssha/nyxx#90]
Feature request: EmbedBuilder.fromJSON
Exactly as it seems; creates a new instance of EmbedBuilder but adds elements from a JSON object first.

**Why?**
So embed JSON can be directly copy-pasted from generators like [leovoel's Embed Visualizer](https://leovoel.github.io/embed-visualizer/), making life a bit easier 😀

**Comment by HarryET** [comment]
Addressed in PR #131

**Comment by l7ssha** [comment]
Issue fixed, closing...
